Kassiopeia: Kassiopeia::KSIntCalculatorArgon Class Reference
Kassiopeia::KSIntCalculatorArgon Class Reference abstract
Public Member Functions
virtual void CalculateCrossSection (const KSParticle &aParticle, double &aCrossSection)
virtual void CalculateCrossSection (const double anEnergie, double &aCrossSection)
virtual void CalculateCrossSection (const KSParticle &aParticle, double &aCrossSection)
virtual void CalculateCrossSection (const double anEnergy, double &aCrossSection)
std::map< double, double > * DEBUG_GetSupportingPoints ()
std::map< double, double > * DEBUG_GetSupportingPoints ()
std::map< double *, double > * DEBUG_GetSupportingPointsDiffX ()
virtual double GetDifferentialCrossSectionAt (const double &anEnergy, const double &anAngle) const
Calculates the cross-section for the given energy and angle.
Protected Member Functions
virtual void ComputeSupportingPoints (unsigned int numOfParameters)
Calculates the supporting points for interpolation/extrapolation/... The result is stored in fSupportingPoints and fParameters. Currently it reads the data file and stores the data and the parameters in they corresponding fields.
double GetCrossSectionAt (const double &anEnergy) const
Calculates the cross-section for the given energy. It splits up the energy region into three parts: 1. Energy lower than the lowest data point. Then it calls the virtual method GetLowerExtrapolation. 2. Region of data points. So we can do an interpolation. So it calls GetInterpolation. 3. Extrapolation for higher energies. It calls GetUpperExtrapolation.
virtual double GetEnergyLoss (const double &anEnergy, const double &theta) const =0
Calculates the energy loss.
virtual double GetInterpolation (const double &anEnergy, std::map< double, double >::iterator &point) const
Calculates the cross-section for the interpolation region. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a linear interpolation.
virtual double GetInterpolationForTotalCrossSection (const double &anEnergy, std::map< double, double >::iterator &point) const
Calculates the cross-section for the interpolation region. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a linear interpolation.
virtual double GetLowerExtrapolation (const double &anEnergy, std::map< double, double >::iterator &point) const
Calculates the cross-section for extrapolation at low energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation returns zero.
virtual double GetLowerExtrapolationForTotalCrossSection (const double &anEnergy, std::map< double, double >::iterator &point) const
Calculates the cross-section for extrapolation at low energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation returns zero.
virtual double GetTheta (const double &anEnergy) const
Calculates theta. The current implementation uses GetDifferentialCrossSectionAt().
double GetTotalCrossSectionAt (const double &anEnergy) const
Calculates the cross-section for the given energy. It splits up the energy region into three parts: 1. Energy lower than the lowest data point. Then it calls the virtual method GetLowerExtrapolation. 2. Region of data points. So we can do an interpolation. So it calls GetInterpolation. 3. Extrapolation for higher energies. It calls GetUpperExtrapolation.
virtual double GetUpperExtrapolation (const double &anEnergy, std::map< double, double >::iterator &point) const
Calculates the cross-section for extrapolation at high energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a power law extrapolation with parameters fParameters[0] and fParameters[1].
virtual double GetUpperExtrapolationForTotalCrossSection (const double &anEnergy, std::map< double, double >::iterator &point) const
Calculates the cross-section for extrapolation at high energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a power law extrapolation with parameters fParameters[0] and fParameters[1].
virtual void InitializeDifferentialCrossSection (unsigned int numOfParameters)
Calculates the supporting points for interpolation/extrapolation/... for the differential cross section. The result is stored in fSupportingPointsDifferentialCrossSection and fParametersDifferentialCrossSection. Currently it reads the data file and stores the data and the parameters in they corresponding fields.
virtual void InitializeTotalCrossSection (unsigned int numOfParameters)
Calculates the supporting points for interpolation/extrapolation/... for the total cross section. The result is stored in fSupportingPointsTotalCrossSection and fParametersTotalCrossSection. Currently it reads the data file and stores the data and the parameters in they corresponding fields.
Protected Attributes
std::string fDataFile
std::string fDataFileDifferentialCrossSection
std::string fDataFileTotalCrossSection
katrin::KMathBilinearInterpolator< double > * fDifferentialCrossSectionInterpolator
Two dimensional interpolator for calculations of differential cross-section.
std::vector< double > * fParameters
std::vector< double > * fParametersTotalCrossSection
std::map< double, double > * fSupportingPoints
std::map< double, double > * fSupportingPointsTotalCrossSection
Detailed Description
Definition at line 98 of file KSIntCalculatorArgon.h.
Member Function Documentation
void Kassiopeia::KSIntCalculatorArgon::ComputeSupportingPoints (unsigned int numOfParameters) protected virtual
Calculates the supporting points for interpolation/extrapolation/... The result is stored in fSupportingPoints and fParameters. Currently it reads the data file and stores the data and the parameters in they corresponding fields.
numOfParameters The number of parameters which have to read in before data
Definition at line 235 of file KSIntCalculatorArgon_old.cxx.
double Kassiopeia::KSIntCalculatorArgon::GetCrossSectionAt (const double & anEnergy) const protected
Calculates the cross-section for the given energy. It splits up the energy region into three parts: 1. Energy lower than the lowest data point. Then it calls the virtual method GetLowerExtrapolation. 2. Region of data points. So we can do an interpolation. So it calls GetInterpolation. 3. Extrapolation for higher energies. It calls GetUpperExtrapolation.
Returns
Cross-section
Definition at line 212 of file KSIntCalculatorArgon_old.cxx.
double Kassiopeia::KSIntCalculatorArgon::GetDifferentialCrossSectionAt (const double & anEnergy, const double & anAngle) const virtual
Calculates the cross-section for the given energy and angle.
Parameters
anEnergy Energy in eV
anAngle Angle in degree
Returns
Cross-section
Definition at line 114 of file KSIntCalculatorArgon.cxx.
References fDifferentialCrossSectionInterpolator.
Referenced by GetTheta(), and InitializeTotalCrossSection().
virtual double Kassiopeia::KSIntCalculatorArgon::GetEnergyLoss (const double & anEnergy, const double & theta) const protected pure virtual
Calculates the energy loss.
Returns
Energy loss
Referenced by InitializeTotalCrossSection().
double Kassiopeia::KSIntCalculatorArgon::GetInterpolation (const double & anEnergy, std::map< double, double >::iterator & point) const protected virtual
Calculates the cross-section for the interpolation region. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a linear interpolation.
Returns
Cross-section
Definition at line 191 of file KSIntCalculatorArgon_old.cxx.
double Kassiopeia::KSIntCalculatorArgon::GetInterpolationForTotalCrossSection (const double & anEnergy, std::map< double, double >::iterator & point) const protected virtual
Calculates the cross-section for the interpolation region. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a linear interpolation.
Returns
Cross-section
Definition at line 42 of file KSIntCalculatorArgon.cxx.
Referenced by GetTotalCrossSectionAt().
double Kassiopeia::KSIntCalculatorArgon::GetLowerExtrapolation (const double & anEnergy, std::map< double, double >::iterator & point) const protected virtual
Calculates the cross-section for extrapolation at low energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation returns zero.
Returns
Cross-section
Definition at line 207 of file KSIntCalculatorArgon_old.cxx.
double Kassiopeia::KSIntCalculatorArgon::GetLowerExtrapolationForTotalCrossSection (const double & anEnergy, std::map< double, double >::iterator & point) const protected virtual
Calculates the cross-section for extrapolation at low energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation returns zero.
Returns
Cross-section
Definition at line 62 of file KSIntCalculatorArgon.cxx.
Referenced by GetTotalCrossSectionAt().
double Kassiopeia::KSIntCalculatorArgon::GetTheta (const double & anEnergy) const protected virtual
Calculates theta. The current implementation uses GetDifferentialCrossSectionAt().
Returns
theta in radians
Definition at line 67 of file KSIntCalculatorArgon.cxx.
References GetDifferentialCrossSectionAt().
Referenced by InitializeTotalCrossSection().
double Kassiopeia::KSIntCalculatorArgon::GetTotalCrossSectionAt (const double & anEnergy) const protected
Calculates the cross-section for the given energy. It splits up the energy region into three parts: 1. Energy lower than the lowest data point. Then it calls the virtual method GetLowerExtrapolation. 2. Region of data points. So we can do an interpolation. So it calls GetInterpolation. 3. Extrapolation for higher energies. It calls GetUpperExtrapolation.
Returns
Cross-section
Definition at line 89 of file KSIntCalculatorArgon.cxx.
References GetInterpolationForTotalCrossSection(), GetLowerExtrapolationForTotalCrossSection(), and GetUpperExtrapolationForTotalCrossSection().
Referenced by InitializeTotalCrossSection().
double Kassiopeia::KSIntCalculatorArgon::GetUpperExtrapolation (const double & anEnergy, std::map< double, double >::iterator & point) const protected virtual
Calculates the cross-section for extrapolation at high energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a power law extrapolation with parameters fParameters[0] and fParameters[1].
Returns
Cross-section
Definition at line 202 of file KSIntCalculatorArgon_old.cxx.
double Kassiopeia::KSIntCalculatorArgon::GetUpperExtrapolationForTotalCrossSection (const double & anEnergy, std::map< double, double >::iterator & point) const protected virtual
Calculates the cross-section for extrapolation at high energies. The parameter "point" is the data point which is the first element in the map which goes after "anEnergy". The current implementation executes a power law extrapolation with parameters fParameters[0] and fParameters[1].
Returns
Cross-section
Definition at line 55 of file KSIntCalculatorArgon.cxx.
Referenced by GetTotalCrossSectionAt().
void Kassiopeia::KSIntCalculatorArgon::InitializeDifferentialCrossSection (unsigned int numOfParameters) protected virtual
Calculates the supporting points for interpolation/extrapolation/... for the differential cross section. The result is stored in fSupportingPointsDifferentialCrossSection and fParametersDifferentialCrossSection. Currently it reads the data file and stores the data and the parameters in they corresponding fields.
numOfParameters The number of parameters which have to read in before data
Definition at line 136 of file KSIntCalculatorArgon.cxx.
References fDifferentialCrossSectionInterpolator, and Kassiopeia::KSIntCalculatorArgonDifferentialCrossSectionReader::GetData().
Referenced by InitializeTotalCrossSection().
void Kassiopeia::KSIntCalculatorArgon::InitializeTotalCrossSection (unsigned int numOfParameters) protected virtual
Calculates the supporting points for interpolation/extrapolation/... for the total cross section. The result is stored in fSupportingPointsTotalCrossSection and fParametersTotalCrossSection. Currently it reads the data file and stores the data and the parameters in they corresponding fields.
numOfParameters The number of parameters which have to read in before data
Definition at line 184 of file KSIntCalculatorArgon.cxx.
References fDifferentialCrossSectionInterpolator, Kassiopeia::KSIntCalculatorArgonDifferentialCrossSectionReader::GetData(), GetDifferentialCrossSectionAt(), GetEnergyLoss(), GetTheta(), GetTotalCrossSectionAt(), and InitializeDifferentialCrossSection().
The documentation for this class was generated from the following files:
KSIntCalculatorArgon.h
KSIntCalculatorArgon_old.h
KSIntCalculatorArgon.cxx
KSIntCalculatorArgon_old.cxx